name: "release"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: 10
        registry-url: 'https://npm.pkg.github.com'
      run: npm run build
           utils/publish_all_packages.sh --tip-of-tree
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}