name: "release"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Publish 🚀
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - name: Build
      run: npm install && npm run build

    - uses: actions/setup-node@master
      with:
        node-version: 12
        scope: '@fluxoutdoor'
        always-auth: true
    - name: Publish
      run: |
        printf "registry=https://npm.pkg.github.com/fluxoutdoor/\n//npm.pkg.github.com/:_authToken=${{ secrets.GH_Packages }}" > ~/.npmrc
        cat ~/.npmrc
        node ./packages/build_package.js playwright "$PWD/playwright.tgz"
        npm publish $PWD/playwright.tgz
      env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_Packages }}