name: "release"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Publish 🚀
    runs-on: ubuntu-18.04
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Build
      run: npm install && npm run build

    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Publish
      run: |
        printf "registry=https://npm.pkg.github.com/fluxoutdoor/\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
        utils/publish_all_packages.sh --tip-of-tree