name: "release"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - uses: microsoft/playwright-github-action@v1
    - name: Build 
      run: npm ci
           npm run build
    - name: Publish
      run: utils/publish_all_packages.sh --tip-of-tree
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}